/// <reference types="cypress" />

describe('Accont testing', ()=> {
    const userlogin = 'cypresstestlogin'
    const password = 'cypresstestpassword'
    const email = 'cypresstestemail@mailbox.ua'
    const invalidPassword = 'cypressinvalidpass'
    const invalidemail = 'cypressinvalidmail@mail.ua'
    it('Register User', ()=>{
        cy.visit('/')
        cy.contains('Signup / Login').click()
        cy.get('[data-qa="signup-name"]').type(userlogin)
        cy.get('[data-qa="signup-email"]').type(email)
        cy.get('[data-qa="signup-button"]').click()
        cy.url().should('include', '/signup')
        cy.get('#id_gender1').check()
        cy.get('[data-qa="name"]').should('have.value', userlogin)
        cy.get('[data-qa="email"]').should('have.value', email)
        cy.get('[data-qa="password"]').type(password)
        cy.get('[data-qa="days"]').select('31')
        cy.get('[id="months"]').select('August')
        cy.get('[data-qa="years"]').select('1990')
        cy.get('#newsletter').check()
        cy.get('#optin').check()
        cy.get('[data-qa="first_name"]').type('Bohdan')
        cy.get('[data-qa="last_name"]').type('Vdovychenko')
        cy.get('[data-qa="company"]').type('Testlearning')
        cy.get('[data-qa="address"]').type('Sacramento')
        cy.get('[data-qa="address2"]').type('Fresno')
        cy.get('[data-qa="country"]').select('United States')
        cy.get('[data-qa="state"]').type('California')
        cy.get('[data-qa="city"]').type('Sacramento')
        cy.get('[data-qa="zipcode"]').type('94207')
        cy.get('[data-qa="mobile_number"]').type('646 666 7587')
        cy.get('[data-qa="create-account"]').click()
        cy.url().should('include', '/account_created')
        cy.get('[data-qa="continue-button"]').click()
    })
    it('Register User with existing email', ()=>{
        cy.visit('/')
        cy.contains('Signup / Login').click()
        cy.get('[data-qa="signup-name"]').type(userlogin)
        cy.get('[data-qa="signup-email"]').type(email)
        cy.get('[data-qa="signup-button"]').click()
        cy.contains('Email Address already exist!').should('be.visible')
    })
    it('Login and logout', ()=>{
        cy.visit('/')
        cy.contains('Signup / Login').click()
        cy.url().should('include', '/login')
        cy.get('[data-qa="login-email"]').type(email)
        cy.get('[data-qa="login-password"]').type(password)
        cy.get('[data-qa="login-button"]').click()
        cy.contains(`Logged in as ${userlogin}`)
        cy.contains('Logout').click()
        cy.url().should('include', '/login')
    })
        it('Login and delete account', ()=>{
        cy.visit('/')
        cy.contains('Signup / Login').click()
        cy.url().should('include', '/login')
        cy.get('[data-qa="login-email"]').type(email)
        cy.get('[data-qa="login-password"]').type(password)
        cy.get('[data-qa="login-button"]').click()
        cy.contains(`Logged in as ${userlogin}`)
        cy.contains('Delete Account').click()
        cy.get('[data-qa="continue-button"]').click()
    })
        it('Login with incorrect email and password', () =>{
        cy.visit('/')
        cy.contains('Signup / Login').click()
        cy.url().should('include', '/login')
        cy.get('[data-qa="login-email"]').type(invalidemail)
        cy.get('[data-qa="login-password"]').type(invalidPassword)
        cy.get('[data-qa="login-button"]').click()
        cy.contains('Your email or password is incorrect!').should('be.visible')
    })
})